---
title: "ENVS 193DS Spring 2026 Final"
author: "Elena Donelson"
date: today
format:
  pdf:
    toc: true
    toc-depth: 3
editor: source
---

[Link to GitHub repository](https://github.com/elenadonelson/ENVS-193DS_spring-2026_final.git)

# Setup

```{r}
#| message: false
#| warning: false

# loading packages
library(tidyverse)
library(janitor)
library(gt)
library(here)

# reading in data
est_data <- read_csv(here("data", "nest_data_final.csv"))
```

# Problem 1. Research writing

## a.

In part 1, they likely used a logistic regression because they were testing whether distance to the water edge predicts the probability of American Avocet microhabitat use.

In part 2, they likely used a chi-square test of independence because they were testing whether there is a relationship between bird species and habitat type, which are both categorical variables.

## b.

For part 1, the probability of American Avocet microhabitat use changed with distance from the water edge, suggesting that distance to water may influence where American Avocets choose to use habitat.

For part 2, American Avocets, Forster's Terns, and Black-necked Stilts used habitats differently, suggesting that each species may have different habitat preferences within the San Francisco Bay.













